// parent positions are zero indexed for each existing mastery in tree
var data = [
		// offensive
    [
        {
            index: 1,
            name: "Summoner's Wrath",
            ranks: 1,
            desc: "Improves the following Summoner Spells:\n\n|Exhaust:| Reduces target's Magic Resist and Armor by 10\n|Ignite:| Increases Ability Power and Attack Damage by 5 while on cooldown\n|Ghost:| Increases Movement Speed bonus to 35%\n|Garrison:| Allied Garrisoned turrets deal 50% splash damage.",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Fury",
            ranks: 4,
            desc: "+#% Attack Speed",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 3,
            name: "Sorcery",
            ranks: 4,
            desc: "+#% Cooldown Reduction",
            rankInfo: [1, 2, 3, 4],
        },
        {
            index: 4,
            name: "Butcher",
            ranks: 1,
            desc: "Basic attacks deal # bonus damage to minions and monsters",
            rankInfo: [2, 4],
        },
		{
            index: 5,
            name: "Deadliness",
            ranks: 1,
            perlevel: 1,
            desc: "+# Attack Damage per level\n(# Attack Damage at champion level 18)",
            rankInfo: [0.166, 0.333, 0.498, 0.664],
        },
        {
            index: 6,
            name: "Deadliness",
            ranks: 3,
            perlevel: 1,
            desc: "+# Attack Damage per level\n(# Attack Damage at champion level 18)",
            rankInfo: [0.166, 0.333, 0.498, 0.664],
        },
        {
            index: 7,
            name: "Blast",
            ranks: 3,
            perlevel: 1,
            desc: "+# Ability Power per level\n(# Ability Power at champion level 18)",
            rankInfo: [0.25, 0.5, 0.75, 1],
        },
        {
            index: 8,
            name: "Destruction",
            ranks: 1,
            desc: "Increase damage to turrets by 5%",
            rankInfo: [],
			parent: 3,
        },
        {
            index: 9,
            name: "Havoc",
            ranks: 1,
            desc: "Increases damage dealt by #%",
            rankInfo: [0.67, 1.33, 2],
        },
        {
            index: 10,
            name: "Weapon Expertise",
            ranks: 1,
            desc: "+8% Armor Penetraton",
            rankInfo: [],
			parent: 5,
        },
        {
            index: 11,
            name: "Arcane Knowledge",
            ranks: 1,
            desc: "+8% Magic Penetration",
            rankInfo: [],
			parent: 6,
        },
		{
            index: 12,
            name: "Deadliness",
            ranks: 3,
            perlevel: 1,
            desc: "+# Attack Damage per level\n(# Attack Damage at champion level 18)",
            rankInfo: [0.166, 0.333, 0.498, 0.664],
        },
        {
            index: 13,
            name: "Lethality",
            ranks: 1,
            desc: "+#% Critical Strike Damage\n (#% for melee champions)",
            rankInfo: [2.5, 5],
            rankInfo2: [5, 10],
			parent: 8,
        },
        {
            index: 14,
            name: "Brute Force",
            ranks: 3,
            desc: "+# Attack Damage",
            rankInfo: [1.5, 3],
        },
        {
            index: 15,
            name: "Mental Force",
            ranks: 3,
            desc: "# Ability Power",
            rankInfo: [2, 4, 6],
        },
        {
            index: 16,
            name: "Spellsword",
            ranks: 1,
            desc: "Deals 5% of your Ability Power in magic damage to the target on each basic attack",
            rankInfo: [],
			parent: 11,
        },
        {
            index: 17,
            name: "Frenzy",
            ranks: 1,
            desc: "Grants 10% attack speed for 2 seconds after landing a critical hit",
            rankInfo: [],
        },
        {
            index: 18,
            name: "Sunder",
            ranks: 3,
            desc: "+# Armor Penetration",
            rankInfo: [2, 4, 6],
        },
        {
            index: 20,
            name: "Archmage",
            ranks: 1,
            desc: "Increases Ability Power by #%",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 22,
            name: "Executioner",
            ranks: 1,
            desc: "Increases damage dealt by 5% to targets below 50% Health",
            rankInfo: [],
        },
    ],
        // defensive
    [
        {
            index: 1,
            name: "Summoner's Resolve",
            ranks: 2,
            desc: "Improves the following Summoner Spells:\n\n|Cleanse:| Increases duration of disable reduction by 1 second\n|Heal:| Passively increases Health by 5 per level\n|Smite:| Grants 10 bonus gold on use\n|Barrier:| Increases Barrier shield amount by 20",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Perseverance",
            ranks: 2,
            desc: "Grants up to +# Health Regen per 5 seconds based on missing Health",
            rankInfo: [2, 4, 6],
        },
        {
            index: 3,
            name: "Durability",
            ranks: 2,
            perlevel: 1,
            desc: "+# Health per level\n(+# Health at champion level 18)",
            rankInfo: [1.5, 3, 4.5, 6],
        },
        {
            index: 4,
            name: "Tough Skin",
            ranks: 2,
            desc: "Reduces damage taken from monsters by #",
            rankInfo: [1, 2],
        },
        {
            index: 5,
            name: "Hardiness",
            ranks: 1,
            desc: "+# Armor",
            rankInfo: [2, 4, 6],
			parent: 0,
        },
        {
            index: 6,
            name: "Resistance",
            ranks: 3,
            desc: "+# Magic Resist",
            rankInfo: [2, 4, 6],
        },
        {
            index: 8,
            name: "Bladed Armor",
            ranks: 1,
            desc: "Deals 6 damage to any enemy monster that attacks you",
            rankInfo: [],
			parent: 3,
        },
        {
            index: 9,
            name: "Unyielding",
            ranks: 1,
            desc: "Reduces the damage taken from enemy champions by #",
            rankInfo: [1, 2],
        },
        {
            index: 10,
            name: "Relentless",
            ranks: 1,
            desc: "Reduces the effectiveness of slows by #%",
            rankInfo: [7.5, 15],
			parent: 5,
        },
        {
            index: 11,
            name: "Veteran's Scars",
            ranks: 3,
            desc: "+30 Health",
            rankInfo: [],
        },
        {
            index: 12,
            name: "Safeguard",
            ranks: 3,
            desc: "Reduces damage taken from turrets by 5%",
            rankInfo: [],
        },
        {
            index: 13,
            name: "Block",
            ranks: 3,
            desc: "Reduces damage taken from champion basic attacks by 3",
            rankInfo: [],
        },
        {
            index: 14,
            name: "Tenacious",
            ranks: 1,
            desc: "Reduces the duration of crowd control effects by #% (stacks multiplicatively with Tenacity)",
            rankInfo: [5, 10, 15],
        },
        {
            index: 15,
            name: "Juggernaut",
            ranks: 1,
            desc: "Increases your maximum Health by #%",
            rankInfo: [1.5, 2.75, 4],
			parent: 9,
        },
        {
            index: 16,
            name: "Defender",
            ranks: 1,
            desc: "Grants +1 Armor and Magic Resist for each nearby enemy champion",
            rankInfo: [],
			parent: 10,
        },
        {
            index: 17,
            name: "Legendary Armor",
            ranks: 1,
            desc: "Increases bonus Armor and Magic Resist by +#%",
            rankInfo: [2, 4, 6],
        },
        {
            index: 18,
            name: "Good Hands",
            ranks: 4,
            desc: "Reduce time spent dead by 10%",
            rankInfo: [],
        },
        {
            index: 19,
            name: "Reinforced Armor",
            ranks: 1,
            desc: "Reduce damage taken from critical strikes by 10%",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Honor Guard",
            ranks: 1,
            desc: "Reduces damage taken from all sources by 3%",
            rankInfo: [],
        },
    ],
		// utility
    [
        {
            index: 1,
            name: "Summoner's Insight",
            ranks: 1,
            desc: "Improves the following Summoner Spells:\n\n|Teleport:| Reduces cast time by # second\n|Revive:| Grants bonus Health on Revive for 2 minutes\n|Flash:| Reduces cooldown by 15 seconds\n|Clarity:| Increases Mana restored by 25%\n|Clairvoyance:| Grants additional vision of enemy units revealed",
            rankInfo: [0.5],
        },
        {
            index: 2,
            name: "Wanderer",
            ranks: 3,
            desc: "Grants +#% increased Movement Speed when out of combat",
            rankInfo: [0.66, 1.33, 2],
        },
        {
            index: 3,
            name: "Meditation",
            ranks: 3,
            desc: "+# Mana Regen per 5 seconds",
            rankInfo: [1, 2, 3],
        },
        {
            index: 4,
            name: "Improved Recall",
            ranks: 1,
            desc: "Reduces the cast time of Recall by 1 second and Enhanced Recall by # seconds",
            rankInfo: [0.5],
        },
        {
            index: 6,
            name: "Scout",
            ranks: 3,
            desc: "Wards gain 25% increased vision range for the first 3 seconds after placing them",
            rankInfo: [],
        },
        {
            index: 7,
            name: "Mastermind",
            ranks: 1,
            desc: "Reduces the cooldown of Summoner Spells by #%",
            rankInfo: [4, 7, 10],
			parent: 2,
        },
        {
            index: 8,
            name: "Expanded Mind",
            ranks: 1,
            perlevel: 1,
            desc: "+# mana per level (+# at level 18)",
            rankInfo: [4, 7, 10],
        },
        {
            index: 9,
            name: "Artifacer",
            ranks: 3,
            desc: "Reduces the cooldown of activated items by #%",
            rankInfo: [7.5, 15],
        },
        {
            index: 10,
            name: "Greed",
            ranks: 1,
            desc: "Grants an additional +# gold every 10 seconds",
            rankInfo: [0.5, 1, 1.5, 2],
        },
        {
            index: 11,
            name: "Runic Affinity",
            ranks: 3,
            desc: "Increases the duration of shrine, relic, quest, and neutral monster buffs by 20%",
            rankInfo: [],
        },
        {
            index: 12,
            name: "Vampirism",
            ranks: 1,
            desc: "+#% Lifesteal and Spell Vamp",
            rankInfo: [1, 2, 3],
			parent: 6,
        },
        {
            index: 13,
            name: "Biscuiteer",
            ranks: 1,
            desc: "Start the game with a regenerative biscuit that restores 80 Health and 50 Mana over 10 seconds",
            rankInfo: [],
			parent: 7,
        },
        {
            index: 14,
            name: "Wealth",
            ranks: 1,
            desc: "Increases starting gold by #",
            rankInfo: [25, 50],
        },
        {
            index: 15,
            name: "Awareness",
            ranks: 3,
            desc: "Increases Experience earned by #%",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 16,
            name: "Strength of Spirit",
            ranks: 2,
            desc: "Up to +# Health Regen per 5 seconds for each 400 Mana you possess",
            rankInfo: [1, 2, 3],
        },
        {
            index: 18,
            name: "Explorer",
            ranks: 1,
            desc: "On Summoners Rift, grants a Ward at the start of the game that can be placed to reveal the surrounding area for 60 seconds. On all other maps, grants 25 starting gold.",
            rankInfo: [],
			parent: 12,
        },
        {
            index: 19,
            name: "Pickpocket",
            ranks: 3,
            desc: "Grants 5 gold for melee champions and 3 gold for ranged champions each time you perform a basic attack against an enemy champion (5 second cooldown)",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Nimble",
            ranks: 1,
            desc: "Grants 3% increased Movement Speed",
            rankInfo: [],
        },
    ]
];
