// parent positions are zero indexed for each existing mastery in tree
var data = [
		// offensive
    [
        {
            index: 1,
            name: "Double-Edged Sword",
            ranks: 1,
            desc: "Melee - Deal an additional 2% damage and receive an additional 1% damage\n\nRanged- Deal an additional 1.5% damage and receive an additional 1.5% damage",
            rankInfo: [],
        },
        {
            index: 2,
            name: "Fury",
            ranks: 4,
            desc: "+#% Attack Speed",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 3,
            name: "Sorcery",
            ranks: 4,
            desc: "+#% Cooldown Reduction",
            rankInfo: [1.25, 2.5, 3.75, 5],
        },
        {
            index: 4,
            name: "Butcher",
            ranks: 1,
            desc: "Basic attacks and single target spells deal an additional 2 damage to minions and monsters\n\nThis does not trigger off of area of effect damage or damage over time effects",
            rankInfo: [],
        },
		{
            index: 5,
            name: "Expose Weakness",
            ranks: 1,
            perlevel: 1,
            desc: "Damaging an enemy with a spell increases allied champions damage to that enemy by 1% for the next 3 seconds",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Brute Force",
            ranks: 3,
            perlevel: 1,
            desc: "+# Attack Damage at level 18\n(+# Attack Damage per level)",
            rankInfo: [4, 7, 10],
			rankInfo2: [0.22, 0.39, 0.55],
        },
        {
            index: 7,
            name: "Mental Force",
            ranks: 3,
            perlevel: 1,
            desc: "+# Ability Power at level 18\n(# Ability Power per level)",
            rankInfo: [6, 11, 16],
			rankInfo2: [0.33, 0.61, 0.89],
        },
        {
            index: 8,
            name: "Feast",
            ranks: 1,
            desc: "Killing a unit restores 3 Health and 1 Mana",
            rankInfo: [],
			parent: 3,
        },
        {
            index: 9,
            name: "Spell Weaving",
            ranks: 1,
            desc: "Damaging an enemy champion with a Basic Attack increases Spell Damage by 1%, stacking up to 3 times (max 3% damage increase)",
            rankInfo: [],
        },
        {
            index: 10,
            name: "Martial Mastery",
            ranks: 1,
            desc: "+4 Attack Damage",
            rankInfo: [],
			parent: 5,
        },
        {
            index: 11,
            name: "Arcane Mastery",
            ranks: 1,
            desc: "+6 Ability Power",
            rankInfo: [],
			parent: 6,
        },
		{
            index: 12,
            name: "Executioner",
            ranks: 3,
            perlevel: 1,
            desc: "Increases damage dealt to champions below #% Health by 5%",
            rankInfo: [20, 35, 50],
        },
        {
            index: 13,
            name: "Blade Weaving",
            ranks: 1,
            desc: "Damaging an enemy champion with a spell increases Basic Attack Damage by 1%, stacking up to 3 times (max 3% damage increase).\n\nThis cannot trigger more than once a second",
            rankInfo: [2.5, 5],
            rankInfo2: [5, 10],
			parent: 8,
        },
        {
            index: 14,
            name: "Warlord",
            ranks: 3,
            desc: "Increases bonus Attack Damage by #%",
            rankInfo: [2, 3.5, 5],
        },
        {
            index: 15,
            name: "Archmage",
            ranks: 3,
            desc: "Increases Ability Power by #%",
            rankInfo: [2, 3.5, 5],
        },
        {
            index: 16,
            name: "Dangerous Game",
            ranks: 1,
            desc: "Killing a champion restores 5% missing Health and Mana",
            rankInfo: [],
			parent: 11,
        },
        {
            index: 17,
            name: "Frenzy",
            ranks: 1,
            desc: "Critical hits grant +5% Attack Speed for 3 seconds (stacks up to 3 times)",
            rankInfo: [],
        },
        {
            index: 18,
            name: "Devastating Strikes",
            ranks: 3,
            desc: "+# Armor and Magic Penetration",
            rankInfo: [2, 4, 6],
        },
        {
            index: 20,
            name: "Arcane Blade",
            ranks: 1,
            desc: "Basic Attacks also deal bonus magic damage equal to 5% of Ability Power",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Havoc",
            ranks: 1,
            desc: "+3% increased damage",
            rankInfo: [],
        },
    ],
        // defensive
    [
        {
            index: 1,
            name: "Block",
            ranks: 2,
            desc: "Reduces incoming damage from champion basic attacks by #",
            rankInfo: [1, 2],
        },
        {
            index: 2,
            name: "Perseverance",
            ranks: 2,
            desc: "+# Health per 5 seconds",
            rankInfo: [1, 2],
        },
        {
            index: 3,
            name: "Enchanted Armor",
            ranks: 2,
            perlevel: 1,
            desc: "Increases bonus Armor and Magic Resistance by #%",
            rankInfo: [2.5, 5],
        },
        {
            index: 4,
            name: "Tough Skin",
            ranks: 2,
            desc: "Reduces damage taken from neutral monsters by #",
            rankInfo: [1, 2],
        },
        {
            index: 5,
            name: "Unyielding",
            ranks: 1,
            desc: "Melee - Reduces all incoming damage from champions by 2\n\nRanged - Reduces all incoming damage from champions by 1",
            rankInfo: [],
			parent: 0,
        },
        {
            index: 6,
            name: "Veteran Scars",
            ranks: 3,
            desc: "+# Health",
            rankInfo: [12, 24, 36],
        },
        {
            index: 8,
            name: "Bladed Armor",
            ranks: 1,
            desc: "Taking Basic Attack Damage from neutral monsters cause them to bleed, dealing damage equal to 1% of their current Health each second\n\nThis does not work against lane minions",
            rankInfo: [],
			parent: 3,
        },
        {
            index: 9,
            name: "Oppression",
            ranks: 1,
            desc: "Reduces damage taken by 2% from enemies that have impaired movement (slows, snares, taunts, stuns, etc)",
            rankInfo: [],
        },
        {
            index: 10,
            name: "Juggernaut",
            ranks: 1,
            desc: "+3% Maximum Health",
            rankInfo: [],
			parent: 5,
        },
        {
            index: 11,
            name: "Hardiness",
            ranks: 3,
            desc: "+# Armor",
            rankInfo: [2, 3.5, 5],
        },
        {
            index: 12,
            name: "Resistance",
            ranks: 3,
            desc: "+# Magic Resistance",
            rankInfo: [2, 3.5, 5],
        },
        {
            index: 13,
            name: "Block",
            ranks: 3,
            desc: "Regenerates #% missing Health every 5 seconds",
            rankInfo: [0.35, 0.675, 1],
        },
        {
            index: 14,
            name: "Tenacious",
            ranks: 1,
            desc: "Reduces the duration of crowd control effects by #% (stacks multiplicatively with Tenacity)",
            rankInfo: [5, 10, 15],
        },
        {
            index: 15,
            name: "Reinforced Armor",
            ranks: 1,
            desc: "Reduces damage taken by Criritcal strikes by 10%",
            rankInfo: [1.5, 2.75, 4],
			parent: 9,
        },
        {
            index: 16,
            name: "Evasive",
            ranks: 1,
            desc: "Reduces damage taken by 4% from Area of Effect magic damage",
            rankInfo: [],
			parent: 10,
        },
        {
            index: 17,
            name: "Second Wind",
            ranks: 1,
            desc: "Increases self-healing, Health regen, Lifesteal, and Spellvamp by 10% when below 25% Health",
            rankInfo: [2, 4, 6],
        },
        {
            index: 18,
            name: "Legendary Guardian",
            ranks: 4,
            desc: "+3 Armor and +3 Magic Resistance for each nearby enemy champion",
            rankInfo: [],
        },
        {
            index: 19,
            name: "Runic Blessing",
            ranks: 1,
            desc: "Start the game with a 50 health shield. This shield regenerates each time after respawning",
            rankInfo: [],
        },
        {
            index: 22,
            name: "Tenacious",
            ranks: 1,
            desc: "Reduces the duration of crowd control effects by 10%",
            rankInfo: [],
        },
    ],
		// utility
    [
        {
            index: 1,
            name: "Phasewalk",
            ranks: 1,
            desc: "Reduces the casting time of Recall by 1 second\n\nDominion - Reduces the casting time of Enchanted Recall by 0.5 seconds",
            rankInfo: [0.5],
        },
        {
            index: 2,
            name: "Fleet of Foot",
            ranks: 3,
            desc: "+#% Movement Speed",
            rankInfo: [0.5, 1, 1.5],
        },
        {
            index: 3,
            name: "Meditation",
            ranks: 3,
            desc: "Restores #% of missing mana every 5 seconds",
            rankInfo: [0.5, 1, 1.5],
        },
        {
            index: 4,
            name: "Scout",
            ranks: 1,
            desc: "Increases the cast range of trinket items by 15%",
            rankInfo: [],
        },
        {
            index: 6,
            name: "Summoner's Inssight",
            ranks: 3,
            desc: "Reduces the cooldown of Summoner Spells by #%",
            rankInfo: [4, 7, 10],
        },
        {
            index: 7,
            name: "Strength of Spirit",
            ranks: 1,
            desc: "+1 Health Regen per 5 seconds for every 300 maximum Mana",
            rankInfo: [],
			parent: 2,
        },
        {
            index: 8,
            name: "Alchemist",
            ranks: 1,
            perlevel: 1,
            desc: "Increases the duration of potions and elixers by 10%",
            rankInfo: [],
        },
        {
            index: 9,
            name: "Greed",
            ranks: 3,
            desc: "+# Gold every 10 seconds",
            rankInfo: [0.5, 1, 1.5],
        },
        {
            index: 10,
            name: "Runic Affinity",
            ranks: 1,
            desc: "Increases the duration of shrine, relic, quest, and neutral monster buffs by 20%",
            rankInfo: [],
        },
        {
            index: 11,
            name: "Vampirism",
            ranks: 1,
            desc: "+#% Lifesteal and Spell Vamp",
            rankInfo: [1, 2, 3],
        },
        {
            index: 12,
            name: "Culinary Master",
            ranks: 1,
            desc: "Health potions are upgraded into Biscuits that restore an additional 20 Health and 10 Mana instantly upon consumption",
            rankInfo: [],
			parent: 6,
        },
        {
            index: 13,
            name: "Scavenger",
            ranks: 1,
            desc: "+1 Gold each time an ally kills a nearby lane minion",
            rankInfo: [],
			parent: 7,
        },
        {
            index: 14,
            name: "Wealth",
            ranks: 1,
            desc: "+40 starting gold",
            rankInfo: [],
        },
        {
            index: 15,
            name: "Expanded Mind",
            ranks: 3,
            desc: "+# Mana",
            rankInfo: [25, 50, 75],
        },
        {
            index: 16,
            name: "Inspiration",
            ranks: 2,
            desc: "+# Experience every 10 seconds while near a higher level allied champion",
            rankInfo: [10, 20],
        },
        {
            index: 18,
            name: "Bandit",
            ranks: 1,
            desc: "Melee - Grants +8 Gold each time an enemy champion is attacked\nThis cannot trigger on the same champion more than once every 5 seconds\n\nRanged - Grants +3 Gold each time an enemy champion is attacked\nThis cannot trigger on the same champion more than once every 5 seconds",
            rankInfo: [],
			parent: 12,
        },
        {
            index: 19,
            name: "Intelligence",
            ranks: 3,
            desc: "+#% Cooldown Reduction and reduces the cooldown of Activated Items by #%",
            rankInfo: [2, 3.5, 5],
			rankInfo2: [8, 14, 20],
        },
        {
            index: 22,
            name: "Nimble",
            ranks: 1,
            desc: "+20 Movement Speed out of combat",
            rankInfo: [],
        },
    ]
];
